[target.aarch64-linux-android]
linker = "/home/svenschmidt75/Android/Sdk/ndk/r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"

[target.armv7-linux-androideabi]
linker = "/home/svenschmidt75/Android/Sdk/ndk/r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang"

[target.i686-linux-android]
linker = "/home/svenschmidt75/Android/Sdk/ndk/r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android26-clang"
